background {
    monitor =
    path = ~/themes/catppuccin-mocha/wallpapers/archtv.png
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(cba6f7)
    inner_color = rgb(1e1e2e)
    font_color = rgb(cdd6f4)
    placeholder_text = <i>Password...</i>
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "<b>$(date +"%H:%M")</b>"
    color = rgba(cdd6f4ff)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}
